# Generated by Django 6.0.6 on 2026-07-08 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_mensagemcontato'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.artigo')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
